const MBTIQuestions = {
  1: {
    question: "WHEN YOU GO SOMEWHERE FOR THE DAY, WOULD YOU RATHER",
    A: "PLAN WHAT YOU WILL DO AND WHEN, OR",
    B: "JUST GO!!",
  },
  2: {
    question: "IF YOU WERE A TEACHER, WOULD YOU RATHER TEACH",
    A: "FACTS-BASED COURSES, OR",
    B: "COURSES INVOLVING OPINION OR THEORY?",
  },
  3: {
    question: "ARE YOU USUALLY",
    A: "A “GOOD MIXER” WITH GROUPS OF PEOPLE, OR",
    B: "RATHER QUIET AND RESERVED?",
  },
  4: {
    question: "DO YOU MORE OFTEN LET",
    A: "YOUR HEART RULE YOUR HEAD. OR",
    B: "YOUR HEAD RULE YOUR HEART?",
  },
  5: {
    question: "IN DOING SOMETHING THAT MANY OTHER PEOPLE DO, WOULD YOU RATHER",
    A: "INVENT A WAY OF YOUR OWN, OR",
    B: "DO IT IN THE ACCEPTED WAY?",
  },
  6: {
    question: "AMONG YOUR FRIENDS ARE YOU",
    A: "FULL OF NEWS ABOUT EVERYBODY, OR",
    B: "ONE OF THE LAST TO HEAR WHAT IS GOING ON?",
  },
  7: {
    question:
      "DOES THE IDEA OF MAKING A LIST OF WHAT YOU SHOULD GET DONE OVER A WEEKEND",
    A: "HELP YOU, OR",
    B: "STRESS YOU, OR",
    C: "POSITIVELY DEPRESS YOU?",
  },
  8: {
    question: "WHEN YOU HAVE A SPECIAL JOB TO DO, DO YOU LIKE TO",
    A: "ORGANIZE IT CAREFULLY BEFORE YOU START, OR",
    B: "FIND OUT WHAT IS NECESSARY AS YOU GO ALONG?",
  },
  9: {
    question: "DO YOU TEND TO HAVE",
    A: "BROAD FRIENDSHIPS WITH MANY DIFFERENT PEOPLE, OR",
    B: "DEEP FRIENDSHIP WITH VERY FEW PEOPLE?",
  },
  10: {
    question: "DO YOU ADMIRE MORE THE PEOPLE WHO ARE",
    A: "NORMAL-ACTING TO NEVER MAKE THEMSELVES THE CENTER OF ATTENTION, OR",
    B:
      "TOO ORIGINAL AND INDIVIDUAL TO CARE WHETHER THEY ARE THE CENTER OF ATTENTION OR NOT",
  },
  11: {
    question: "DO YOU PREFER TO",
    A: "ARRANGE PICNICS, PARTIES ETC, WELL IN ADVANCE, OR",
    B: "BE FREE TO DO WHATEVER TO LOOKS LIKE FUN WHEN THE TIME COMES?",
  },
  12: {
    question: "DO YOU USUALLY GET ALONG BETTER WITH",
    A: "REALISTIC PEOPLE, OR",
    B: "IMAGINATIVE PEOPLE?",
  },
  13: {
    question: "WHEN YOU ARE WITH THE GROUP OF PEOPLE, WOULD YOU USUALLY RATHER",
    A: "JOIN IN THE TALK OF THE GROUP OR",
    B: "STAND BACK AND LISTEN FIRST?",
  },
  14: {
    question: "IS IT A HIGHER COMPLIMENT TO BE CALLED",
    A: "A PERSON OF REAL FEELING, OR",
    B: "A CONSISTENTLY REASONABLE PERSON?",
  },
  15: {
    question: "IN READING FOR PLEASURE, DO YOU",
    A: "ENJOY ODD OR ORIGINAL WAYS OF SAYING THINGS, OR",
    B: "LIKE WRITERS TO SAY EXACTLY WHAT THEY MEAN?",
  },
  16: {
    question: "DO YOU",
    A: "TALK EASILY TO ALMOST ANYONE FOR AS LONG AS YOU HAVE TO, OR",
    B: "FIND A LOT TO SAY ONLY TO CERTAIN PEOPLE OR UNDER CERTAIN CONDITIONS?",
  },
  17: {
    question: "DOES FOLLOWING A SCHEDULE",
    A: "APPEAL TO YOU, OR",
    B: "CRAMP YOU?",
  },
  18: {
    question:
      "WHEN IT IS SETTLED WELL IN ADVANCE THAT YOU WILL DO A CERTAIN THING AT A CERTAIN TIME,DO YOU FIND IT",
    A: "NICE TO BE ABLE TO PLAN ACCORDINGLY, OR",
    B: "A LITTLE UNPLEASANT TO BE TIED DOWN?",
  },
  19: {
    question: "ARE YOU MORE SUCCESSFUL",
    A: "AT FOLLOWING A CAREFULLY WORKED OUT PLAN, OR",
    B: "AT DEALING WITH THE UNEXPECTED AND SEEING QUICKLY WHAT SHOULD BE DONE?",
  },
  20: {
    question: "WOULD YOU RATHER BE CONSIDERED",
    A: "A PRACTICAL PERSON, OR",
    B: "AN OUT-OF-THE-BOX-THINKING PERSON?",
  },
  21: {
    question: "IN A LARGE GROUP, DO YOU MORE OFTEN",
    A: "INTRODUCE OTHERS, OR",
    B: "GET INTRODUCED?",
  },
  22: {
    question: "DO YOU USUALLY",
    A: "VALUE EMOTION MORE THAN LOGIC, OR",
    B: "VALUE LOGIC MORE THAN FEELINGS?",
  },
  23: {
    question: "WOULD YOU RATHER HAVE AS A FRIEND",
    A: "SOMEONE WHO IS ALWAYS COMING UP WITH NEW IDEAS, OR",
    B: "SOMEONE WHO HAS BOTH FEET ON THE GROUND?",
  },
  24: {
    question: "CAN THE NEW PEOPLE YOU MEET TELL WHAT YOU ARE INTERESTED IN",
    A: "RIGHT AWAY,",
    B: "ONLY AFTER THEY REALLY GET TO KNOW YOU?",
  },
  25: {
    question:
      "(ON THIS QUESTION ONLY, IF TWO ANSWERS ARE TRUE, CIRCLE BOTH) IN YOUR DAILY WORK, DO YOU",
    A: "USUALLY PLAN YOUR WORK SO YOU WON’T NEED TO WORK UNDER PRESSURE, OR",
    B: "RATHER ENJOY AN EMERGENCY THAT MAKES YOU WORK AGAINST TIME, OR",
    C: "HATE TO WORK UNDER PRESSURE?",
  },
  26: {
    question: "DO YOU USUALLY",
    A: "SHOW YOUR FEELINGS FREELY, OR",
    B: "KEEP YOUR FEELINGS TO YOURSELF?",
  },
};

export default MBTIQuestions;
